### ISSUE TITLE
Bypass the blockage due to suspicious activity while downloading papers while on the university VPN?

### ISSUE THREAD

**Issue by CWWhitney** [CWWhitney/hosyana_review#20]
Should be a Captcha pop up to answer. If you can identify bikes, bridge or traffic lights you should be able to continue. Otherwise -or- if you are connected with VPN then you have to wait three days and then continue. 

Original Post: 

              Has anybody resolved how to bypass the blockage due to suspicious activity while downloading papers while on the university VPN?

_Originally posted by @andrewm1234 in https://github.com/CWWhitney/hosyana_review/issues/3#issuecomment-1809729073_

**Comment by andrewm1234** [comment]
Ya turned my VPN off and still no ability to use the Captcha : (. So I guess it’s a three day ban.

 

I assume I need to be on the VPN to have the universitys journal access though? Or can I download materials off the VPN to avoid the three day ban?

 

From: Cory Whitney ***@***.***> 
Sent: Tuesday, November 14, 2023 11:51 AM
To: CWWhitney/hosyana_review ***@***.***>
Cc: andrewm1234 ***@***.***>; Mention ***@***.***>
Subject: [CWWhitney/hosyana_review] Bypass the blockage due to suspicious activity while downloading papers while on the university VPN? (Issue #20)

 

Should be a Captcha pop up to answer. If you can identify bikes, bridge or traffic lights you should be able to continue. Otherwise -or- if you are connected with VPN then you have to wait three days and then continue.

Original Post:

          Has anybody resolved how to bypass the blockage due to suspicious activity while downloading papers while on the university VPN?

Originally posted by @andrewm1234 <https://github.com/andrewm1234>  in #3 (comment) <https://github.com/CWWhitney/hosyana_review/issues/3#issuecomment-1809729073>

**Comment by CWWhitney** [comment]
No longer an issues - all documents are now loaded in the Zotero collection
